repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml

-   repo: ssh://git@github.com:mangekyousharingan/seb-dev-libraries.git
    rev: 0.0.9
    hooks:
      - id: pyupgrade
      - id: black
      - id: isort
      - id: flake8
      - id: bandit
      - id: mypy
