[tool.poetry]
name = "project-template"
version = "0.1.0"
description = "Basic project structure"
authors = ["Sebastian Wdowiarz <wdowiarzsebastian@gmail.com>"]
readme = "README.md"
packages = [{include = "project_template"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
